-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR A 
JOIN 
(SELECT AUTHOR_ID, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK 
JOIN BOOK_SALES
USING (BOOK_ID)
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY) B 
USING (AUTHOR_ID)
ORDER BY AUTHOR_ID, CATEGORY DESC 