-- 코드를 입력하세요

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, 
SUM( SALES*PRICE )AS TOTAL_SALES
FROM BOOK AS B INNER JOIN AUTHOR USING(AUTHOR_ID)
INNER JOIN BOOK_SALES USING(BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC 






# SELECT b.AUTHOR_ID, AUTHOR_NAME,a.CATEGORY, SUM(a.PRICE * c.SALES) AS TOTAL_SALES
# FROM BOOK AS a 
# INNER JOIN AUTHOR AS b ON a.AUTHOR_ID = b.AUTHOR_ID
# INNER JOIN BOOK_SALES AS c ON a.BOOK_ID = c.BOOK_ID
# WHERE SUBSTR(c.SALES_DATE,1,7) = '2022-01'
# GROUP BY b.AUTHOR_ID, a.CATEGORY
# ORDER BY b.AUTHOR_ID, a.CATEGORY DESC