-- 코드를 입력하세요
SELECT PRODUCT_CODE, sum(a.PRICE * b.SALES_AMOUNT) as SALES
FROM PRODUCT AS a 
INNER JOIN OFFLINE_SALE as b
ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE