SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I 
INNER JOIN ANIMAL_OUTS AS O 
USING (ANIMAL_ID)
ORDER BY DATEDIFF(O.DATETIME,I.DATETIME) DESC 
LIMIT 2 






# SELECT a.ANIMAL_ID, a.NAME 
# FROM ANIMAL_INS AS a
# LEFT OUTER JOIN ANIMAL_OUTS AS b 
# ON a.ANIMAL_ID = b.ANIMAL_ID
# WHERE b.ANIMAL_ID is not null 
# ORDER BY DATEDIFF(b.DATETIME,a.DATETIME) DESC 
# LIMIT 2