-- 코드를 입력하세요

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R 
WHERE (R.FOOD_TYPE,R.FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FAVORITES       
)
ORDER BY FOOD_TYPE DESC 





# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES	
# FROM REST_INFO
# WHERE (FOOD_TYPE,FAVORITES) in 
# (SELECT FOOD_TYPE, max(FAVORITES)
# FROM REST_INFO
# GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC