-- 코드를 입력하세요
#중고거래 게시물을 3건 이상 등록한 사용자 
# 사용자 ID, 닉네임, 전체 주소, 전화번호 
#회원 ID 내림차순 

SELECT USER_ID, NICKNAME, 
CONCAT(CITY," ",STREET_ADDRESS1," ",STREET_ADDRESS2) AS 전체주소, 
CONCAT_WS("-",SUBSTR(TLNO,1,3),SUBSTR(TLNO,4,4),SUBSTR(TLNO,8,4)) AS 전화번호  
FROM USED_GOODS_USER
WHERE USER_ID IN 
(
    SELECT WRITER_ID 
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID 
    HAVING COUNT (*) >= 3 
) 
ORDER BY USER_ID DESC