-- 코드를 입력하세요
SELECT a.WRITER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4)) AS 전화번호 
FROM USED_GOODS_BOARD AS a 
INNER JOIN USED_GOODS_USER AS b 
ON a.WRITER_ID = b.USER_ID 
GROUP BY a.WRITER_ID
HAVING count(*) >=3
ORDER BY a.WRITER_ID DESC
