# SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME 
# FROM ANIMAL_INS AS a 
# INNER JOIN ANIMAL_OUTS AS b
# ON a.ANIMAL_ID = b.ANIMAL_ID
# WHERE a.SEX_UPON_INTAKE LIKE '%Intact%'
# AND (b.SEX_UPON_OUTCOME LIKE "%Neutered%" OR b.SEX_UPON_OUTCOME LIKE "%Spayed%")
# ORDER BY a.ANIMAL_ID



#중성화 수술을 거친 동물 
#들 : 중성화 x => 나갈 : 중성화 
#아이디, 생물종, 이름 조회 
#아이디 순 정렬 

SELECT INS.ANIMAL_ID , INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS INNER JOIN ANIMAL_OUTS AS OUTS USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE '%INTACT%' AND 
(SEX_UPON_OUTCOME LIKE "%Spayed%" OR SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY ANIMAL_ID 

