#ANIMAL_OUTS : ANIMAL_ID -> ANIMAL_INS의 외래키 
#보호소 IN 중성화 X => 나갈 당시 중성화 o 
#아이디, 생물종, 이름
#아이디 순 

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O 
USING (ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE '%INTACT%'
AND (SEX_UPON_OUTCOME LIKE '%Spayed%' OR  SEX_UPON_OUTCOME LIKE '%Neutered%') 
ORDER BY ANIMAL_ID