-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) as YEAR, 
MONTH(b.SALES_DATE) AS MONTH, 
GENDER , COUNT(DISTINCT a.USER_ID) AS USERS 
FROM USER_INFO AS a 
INNER JOIN ONLINE_SALE AS b
ON a.USER_ID = b.USER_ID
WHERE a.GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER