-- 코드를 입력하세요
#입양 간 기록 O , 들어온 기록 X 

# SELECT O.ANIMAL_ID, O.NAME 
# FROM ANIMAL_OUTS O LEFT OUTER JOIN ANIMAL_INS I 
# ON O.ANIMAL_ID = I.ANIMAL_ID 
# WHERE I.ANIMAL_ID IS NULL




SELECT O.ANIMAL_ID, O.NAME 
FROM ANIMAL_INS AS I 
RIGHT OUTER JOIN ANIMAL_OUTS AS O 
ON O.ANIMAL_ID = I.ANIMAL_ID 
WHERE I.ANIMAL_ID IS NULL




