#Gender : 비어있거나, 0(남자), 1(여자) 
#2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수
#년, 월 별 
#비율은 소수 2째자리에서 반올림 
#년 , 월 오름차순 

#DISTINCT, COUNT 서브 쿼리 

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
COUNT (DISTINCT USER_ID) AS PURCHASED_USERS, 
ROUND( 
    COUNT (DISTINCT USER_ID) / 
    (SELECT COUNT (DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),1) AS PURCHASED_RATIO
FROM USER_INFO INNER JOIN ONLINE_SALE
USING (USER_ID)
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR, MONTH 
ORDER BY YEAR, MONTH 