-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH,
COUNT(DISTINCT(o.USER_ID)) AS PUCHASED_USERS, 
ROUND(
    COUNT(DISTINCT(o.USER_ID))/
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021')
    ,1)
FROM USER_INFO AS u
INNER JOIN ONLINE_SALE AS o 
ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = '2021' 
GROUP BY YEAR, MONTH