-- 코드를 입력하세요
#2021년 
#(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH , 
COUNT(DISTINCT USER_ID) AS PUCHASED_USERS, 
ROUND(
    (COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021')),1) AS PUCHASED_RATIO
FROM USER_INFO 
INNER JOIN ONLINE_SALE
USING (USER_ID)
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR, MONTH 
ORDER BY YEAR, MONTH 






# SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH,
# COUNT(DISTINCT(o.USER_ID)) AS PUCHASED_USERS, 
# ROUND(
#     COUNT(DISTINCT(o.USER_ID))/
#     (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021')
#     ,1)
# FROM USER_INFO AS u
# INNER JOIN ONLINE_SALE AS o 
# ON u.USER_ID = o.USER_ID
# WHERE YEAR(u.JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH