-- 코드를 입력하세요
#2022년 10월 16일에 대여중 => 대여중 // ELSE 대여 가능 (AVAILABILITY)인 자동차
#자동차 ID 기준 내림차순 

SELECT DISTINCT CAR_ID, 
CASE WHEN CAR_ID IN 
(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
) THEN '대여중' 
ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC 