-- 코드를 입력하세요
#입양을 못 간 동물 (OUTER JOIN)
#가장 오래 보호소에 있는 동물 (보호시작일이 가장 빠른 순) 3마리 
# 보호 시작일 순 

SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O 
ON I.ANIMAL_ID = O.ANIMAL_ID 
WHERE O.ANIMAL_ID IS NULL 
ORDER BY DATETIME 
LIMIT 3 