-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT 
INNER JOIN FOOD_ORDER
USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE,"%Y-%m") = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 



# SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(PRICE *AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT AS a
# INNER JOIN FOOD_ORDER AS b 
# ON a.PRODUCT_ID = b.PRODUCT_ID
# WHERE DATE_FORMAT(b.PRODUCE_DATE,"%Y-%m") = '2022-05'
# GROUP BY  a.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID