-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE * TOTAL_AMOUNT AS TOTAL_SALES 
FROM FOOD_PRODUCT A
JOIN
(SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT 
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID) B 
USING(PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 