-- 코드를 입력하세요
WITH DURATION AS 
(
    SELECT DAILY_FEE, CAR_TYPE, HISTORY_ID, CAR_ID, DATEDIFF(END_DATE,START_DATE) +1 AS PERIOD ,
    CASE 
        WHEN DATEDIFF(END_DATE,START_DATE) +1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE) +1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE) +1 >= 7 THEN '7일 이상'
        ELSE NULL END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY INNER JOIN CAR_RENTAL_COMPANY_CAR
    USING (CAR_ID)
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * PERIOD * ((100-IFNULL(DISCOUNT_RATE,0))/100)) AS FEE 
FROM DURATION LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
USING (DURATION_TYPE, CAR_TYPE)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC