-- 코드를 입력하세요

#상반기 
#PK : FLAVOR 
#FK : SHIPMEN_ID => JULY 

#JULY 
#PK : SHIPMENT_ID 
#FK : FLABOR => 상반기 
#같은 아이스크림 맛 : 서로 다른 두 공장 

#7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 
#상위 3개 맛 

SELECT F.FLAVOR 
FROM FIRST_HALF F INNER JOIN 
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY 
    GROUP BY FLAVOR
) AS J 
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC 
LIMIT 3 




# SELECT FLAVOR
# FROM FIRST_HALF AS a 
# INNER JOIN
# (
#     SELECT FLAVOR , SUM(TOTAL_ORDER) AS JULY_SUM
#     FROM JULY
#     GROUP BY FLAVOR
# ) AS b 
# USING(FLAVOR)  
# ORDER BY (TOTAL_ORDER + JULY_SUM) DESC 
# LIMIT 3 

#상반기 => JULY (shipment_id)
#July => 상반기 (FLAOVR)


# SELECT FLAVOR 
# FROM 
# (
#     SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
#     FROM JULY 
#     GROUP BY FLAVOR
# ) AS JULY INNER JOIN FIRST_HALF
# USING (FLAVOR)
# ORDER BY JULY_TOTAL + TOTAL_ORDER DESC
# LIMIT 3