-- 코드를 입력하세요

#상반기 
#PK : FLAVOR 
#FK : SHIPMEN_ID => JULY 

#JULY 
#PK : SHIPMENT_ID 
#FK : FLABOR => 상반기 
#같은 아이스크림 맛 : 서로 다른 두 공장 

#7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 
#상위 3개 맛 

SELECT FLAVOR 
FROM FIRST_HALF INNER JOIN 
(
    SELECT FLAVOR , SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER 
    FROM JULY 
    GROUP BY FLAVOR 
) JULY 
USING (FLAVOR)
ORDER BY (JULY_TOTAL_ORDER + TOTAL_ORDER) DESC 
LIMIT 3 