-- 코드를 입력하세요

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES


# SELECT WRITER_ID,NICKNAME, sum(PRICE) as TOTAL_SALES
# FROM USED_GOODS_BOARD AS a 
# INNER JOIN USED_GOODS_USER AS b 
# ON a.WRITER_ID = b.USER_ID
# WHERE a.STATUS = 'DONE'
# GROUP BY a.WRITER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES