-- 코드를 작성해주세요

WITH GRADE_TABLE AS 
(SELECT EMP_NO,
CASE 
    WHEN 96 <= AVG(SCORE) THEN 20
    WHEN 90 <= AVG(SCORE) THEN 15 
    WHEN 80 <= AVG(SCORE) THEN 10 
    ELSE 0 
 END AS BONUS_PERCENTAGE, 
 CASE 
    WHEN 96 <= AVG(SCORE) THEN 'S'
    WHEN 90 <= AVG(SCORE) THEN 'A' 
    WHEN 80 <= AVG(SCORE) THEN 'B' 
    ELSE 'C' 
 END AS GRADE 
FROM HR_GRADE
GROUP BY EMP_NO) 

SELECT N_T.EMP_NO, EMP_NAME, GRADE, SAL * ((BONUS_PERCENTAGE) /100) BONUS 
FROM GRADE_TABLE G_T 
JOIN 
(SELECT EMP_NO, EMP_NAME, SAL
FROM HR_EMPLOYEES) N_T
ON G_T.EMP_NO = N_T.EMP_NO
ORDER BY EMP_NO










