-- 코드를 입력하세요
#리뷰를 가장 많이 작성한 회원의 "리뷰"
#회원 이름, 리뷰 텍스트, 리뷰 작성일 
#리뷰 작성일 오름, 리뷰 텍스트 오름

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE INNER JOIN REST_REVIEW
USING (MEMBER_ID)
WHERE MEMBER_ID = 
(
    SELECT MEMBER_ID 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1 
) 
ORDER BY REVIEW_DATE, REVIEW_TEXT