-- 코드를 입력하세요
# SELECT MEMBER_NAME, REVIEW_TEXT, 
# DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d")AS REVIEW_DATE
# FROM MEMBER_PROFILE
# INNER JOIN REST_REVIEW
# USING (MEMBER_ID)
# WHERE MEMBER_ID 
# = 
# (
# SELECT MEMBER_ID
# FROM MEMBER_PROFILE 
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC 
# LIMIT 1 
# )
# ORDER BY REVIEW_DATE, REVIEW_TEXT







SELECT a.MEMBER_NAME, b.REVIEW_TEXT, 
DATE_FORMAT(b.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS a 
INNER JOIN REST_REVIEW AS b 
ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID
= (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*)  DESC
LIMIT 1
  )
ORDER BY REVIEW_DATE, REVIEW_TEXT