-- 코드를 작성해주세요

# WITH A AS 
# (
#     SELECT * 
#     FROM ITEM_TREE INNER JOIN ITEM_INFO 
#     USING (ITEM_ID)
# )

# SELECT ITEM_ID, ITEM_NAME, RARITY 
# FROM A 
# WHERE PARENT_ITEM_ID IN 
# (
#     SELECT ITEM_ID 
#     FROM ITEM_INFO
#     WHERE RARITY = 'RARE'
# ) 
# ORDER BY ITEM_ID DESC

SELECT ITEM_ID, ITEM_NAME, RARITY 
FROM ITEM_TREE INNER JOIN ITEM_INFO
USING (ITEM_ID)
WHERE PARENT_ITEM_ID IN 
(
    SELECT DISTINCT ITEM_ID 
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC 