-- 코드를 작성해주세요
select CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
from ECOLI_DATA CHILD
JOIN ECOLI_DATA PARENT
ON (PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE)
AND CHILD.PARENT_ID = PARENT.ID
ORDER BY CHILD.ID