-- 코드를 입력하세요
#보호 시작일(DATETIME)보다 입양일(DATETIME)이 더 빠름 
#보호시작일이 빠른 순 
SELECT I.ANIMAL_ID , I.NAME 
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O 
ON I.ANIMAL_ID = O.ANIMAL_ID 
WHERE I.DATETIME > O.DATETIME 
ORDER BY I.DATETIME 