-- 코드를 입력하세요
#대여 시작일 기준 => 2022년 8월 ~ 2022년 10월까지 5회이상인 자동차들
# 월별 자동차 ID, 총 대여 횟수 
# 월 기준 오름, 자동차 ID 내림 , 
# 대여 0인거 제외 

# SELECT CAR_ID , MONTH(START_DATE) AS MONTH , COUNT(*) AS RECORDS 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
# GROUP BY CAR_ID , MONTH 
# HAVING COUNT(*) > 0 
# ORDER BY MONTH, CAR_ID DESC 

SELECT MONTH(START_DATE) AS MONTH , CAR_ID ,COUNT(*) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN 
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID 
    HAVING COUNT(*) >= 5  
)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID  
HAVING COUNT(*) > 0 
ORDER BY MONTH, CAR_ID DESC

