-- 코드를 작성해주세요


SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR ,MAX_COLONY - SIZE_OF_COLONY AS YEAR_DEV, ID 
FROM ECOLI_DATA A
JOIN 
(SELECT MAX(SIZE_OF_COLONY) MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR) B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV