-- 코드를 입력하세요
SELECT DISTINCT(b.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS a 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b 
ON a.CAR_ID = b.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY b.CAR_ID DESC 