-- 코드를 입력하세요
#자동차 종류 '세단'
# 10월에 대여를 시작한 기록 : START_DATE의 달이 10월 
# 자동차 ID 중복 X 
# 자동차 ID 내림차순 
SELECT DISTINCT CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
USING (CAR_ID)
WHERE MONTH(START_DATE) = 10 
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC 