-- 코드를 작성해주세요
#FISH_NAME_INFO -> NAME 
#JOIN FISH_INFO 
#IN절 : FISH_TYPE, MAX_LENGTH -> FISH_INFO 

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO 
JOIN FISH_NAME_INFO USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN 
(SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
FROM FISH_INFO
WHERE LENGTH IS NOT NULL 
GROUP BY FISH_TYPE)
ORDER BY ID 