-- 코드를 입력하세요
#2022년 1월 
#카테고리 별 도서 판매량 합산 
#카테고리 오름차순 
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK INNER JOIN BOOK_SALES
USING (BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = '2022-01'
GROUP BY CATEGORY 
ORDER BY CATEGORY 
