WITH A AS (SELECT * 
FROM SKILLCODES INNER JOIN DEVELOPERS 
WHERE SKILL_CODE & CODE = CODE) 

SELECT GRADE, ID, EMAIL
FROM (SELECT *, CASE 
        WHEN ID IN ((SELECT ID FROM A WHERE NAME = 'PYTHON') INTERSECT (SELECT ID FROM A WHERE CATEGORY = 'FRONT END')) THEN 'A'
        WHEN ID IN (SELECT ID FROM A WHERE NAME = 'C#') THEN 'B'
        WHEN ID IN (SELECT ID FROM A WHERE CATEGORY = 'FRONT END') THEN 'C' END AS GRADE 
FROM DEVELOPERS) B
WHERE GRADE IS NOT NULL 
ORDER BY GRADE, ID 
