-- 코드를 입력하세요
# SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
# FROM BOOK AS a 
# INNER JOIN AUTHOR as b
# ON a.AUTHOR_ID = b.AUTHOR_ID
# WHERE category = '경제'
# ORDER BY PUBLISHED_DATE

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK 
INNER JOIN AUTHOR 
USING (AUTHOR_ID)
WHERE CATEGORY = "경제"
ORDER BY PUBLISHED_DATE


